"""Backfill: apply rule-based decision to all existing daily_report records.

Phase 2 (2026-07-10): re-derive operation_advice for all 10 days of
existing reports using the new rule-based engine. Preserves LLM's
original op in llm_original_op + records decision_reason.

Phase 7 (2026-07-17): Re-run after Phase 6 added VALUE rule (priority 0).
The script now ALWAYS re-applies the rule (overrides existing) using
llm_original_op as the input. signal_score is re-computed via
predict_win_probability() which uses the latest LR weights.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import sqlite3

from src.signal_decision import (
    apply_to_snapshot, predict_win_probability, extract_matched_rule,
)

DB_PATH = "/Users/kenken/Documents/dsa-hk/data/dsa_hk.db"


def main():
    con = sqlite3.connect(DB_PATH)
    con.row_factory = sqlite3.Row

    # Only backfill the 14-day audit window (6/26 - 7/14).
    # 7/15/7/16 records will be generated by the daily pipeline.
    rows = con.execute("""
        SELECT id, code, report_date, score, sentiment, trend,
               operation_advice, llm_original_op, signal_score,
               score_breakdown_json, data_snapshot_json, decision_reason
        FROM daily_report
        WHERE report_date >= '2026-06-26' AND report_date <= '2026-07-14'
        ORDER BY report_date, code
    """).fetchall()
    print(f"Backfilling {len(rows)} records (2026-06-26 to 2026-07-14)")

    updated = 0
    unchanged = 0
    op_changes = {"BUY→BUY": 0, "BUY→HOLD": 0, "HOLD→HOLD": 0, "HOLD→BUY": 0}
    rule_dist = {}

    for r in rows:
        rid = r["id"]
        old_op = r["operation_advice"]
        # Use existing llm_original_op as the LLM's original; if null, use current op
        llm_orig = r["llm_original_op"] or r["operation_advice"]
        try:
            sb = json.loads(r["score_breakdown_json"] or "{}")
        except Exception:
            sb = {}
        try:
            snap = json.loads(r["data_snapshot_json"] or "{}")
        except Exception:
            snap = {}
        sector = (snap.get("sector") or "").strip()

        # Re-apply rule
        decision = apply_to_snapshot(
            llm_op=llm_orig,
            llm_sentiment=r["sentiment"] or "",
            llm_trend=r["trend"] or "",
            score_breakdown=sb,
            data_snapshot=snap,
            sector=sector,
        )
        new_op = decision.op
        new_reason = f"[{decision.matched_rule}] {decision.reason}"

        # Re-compute signal_score using latest LR
        chg = (snap or {}).get("change_pct") or 0
        new_score = predict_win_probability(
            m=sb.get("momentum_score") or 0,
            of=sb.get("order_flow_score") or 0,
            v=sb.get("value_score") or 0,
            q=sb.get("quality_score") or 0,
            chg=chg,
            sentiment=r["sentiment"] or "",
            matched_rule=decision.matched_rule,
        )

        # Track stats
        rule_dist[decision.matched_rule] = rule_dist.get(decision.matched_rule, 0) + 1
        op_key = f"{'BUY' if '買入' in old_op else 'HOLD'}→{'BUY' if '買入' in new_op else 'HOLD'}"
        op_changes[op_key] = op_changes.get(op_key, 0) + 1

        if new_op == old_op and new_reason == r["decision_reason"] and new_score == r["signal_score"]:
            unchanged += 1
            continue

        con.execute(
            """UPDATE daily_report
               SET operation_advice=?, decision_reason=?, signal_score=?, llm_original_op=?
               WHERE id=?""",
            (new_op, new_reason, new_score, llm_orig, rid),
        )
        updated += 1
        if updated <= 8:
            print(f"  {r['code']:<10} {r['report_date']}: {old_op} → {new_op} "
                  f"[{decision.matched_rule}], score {r['signal_score']} → {new_score}")

    con.commit()
    con.close()

    print(f"\nDone: {updated} updated, {unchanged} unchanged")
    print(f"\nOp change distribution:")
    for k, n in sorted(op_changes.items()):
        print(f"  {k}: {n}")
    print(f"\nNew rule distribution:")
    for r, n in sorted(rule_dist.items(), key=lambda x: -x[1]):
        print(f"  {r:<20} {n:>5}")


if __name__ == "__main__":
    main()
